from __future__ import annotations

from typing import Tuple

SIDM_LAHIRI: int
SUN: int
MOON: int
MARS: int
MERCURY: int
JUPITER: int
VENUS: int
SATURN: int
MEAN_NODE: int
CALC_RISE: int
CALC_SET: int
BIT_DISC_CENTER: int

def set_ephe_path(path: str | bytes) -> None: ...
def set_sid_mode(mode: int) -> None: ...
def julday(year: int, month: int, day: int, hour: float) -> float: ...
def revjul(jd: float) -> Tuple[int, int, int, float]: ...
def houses(jd: float, latitude: float, longitude: float) -> Tuple[Tuple[float, ...], Tuple[float, ...]]: ...
def get_ayanamsa_ut(jd: float) -> float: ...
def calc_ut(jd: float, body: int) -> Tuple[Tuple[float, ...], int]: ...
def rise_trans(jd: float, body: int, rsmi: int, geopos: Tuple[float, float, float], atpress: float, attemp: float) -> Tuple[int, float]: ...
